management:
  tracing:
    sampling:
      probability: ${TRACING_SAMPLE_PROBABILITY:1.0}
    export:
      zipkin:
        enabled: ${ZIPKIN_ENABLED:true}
        endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false

server:
  port: ${SERVER_PORT:9000}
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEY_STORE:file:../ssl/keystore.p12}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:changeit}
    key-store-type: ${SSL_KEY_STORE_TYPE:PKCS12}
    key-alias: ${SSL_KEY_ALIAS:auth}

spring:
  application:
    name: auth
  config:
    import: "configserver:${CONFIG_SERVER_URL:https://localhost:8888}"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    config:
      tls:
        enabled: ${CONFIG_TLS_ENABLED:true}
        trust-store: ${CONFIG_TLS_TRUST_STORE:file:../ssl/truststore.p12}
        trust-store-password: ${CONFIG_TLS_TRUST_STORE_PASSWORD:changeit}
        trust-store-type: PKCS12

eureka:
  client:
    tls:
      enabled: ${EUREKA_TLS_ENABLED:true}
      trust-store: ${COMMON_TLS_TRUST_STORE_PATH:file:../ssl/truststore.p12}
      trust-store-password: ${SSL_KEY_STORE_PASSWORD:changeit}
      trust-store-type: PKCS12
