spring:
  application:
    name: discovery
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:eureka}
      password: ${SPRING_SECURITY_USER_PASSWORD:changeme}

server:
  port: 8761
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEY_STORE:file:../ssl/keystore.p12}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:changeit}
    key-store-type: ${SSL_KEY_STORE_TYPE:PKCS12}
    key-alias: ${SSL_KEY_ALIAS:discovery}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:${server.port}/eureka/
